name: Tests

on: push

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:12-alpine'
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run build
      run: npm run build --if-present
    - name: Run the test suite
      run: npm test